### ISSUE TITLE
make command - Unexpected token < in JSON

### ISSUE THREAD

**Issue by indranilokg** [oktadev/byob-dashboard#32]
**make all** is failing with the following error -
 **SyntaxError: Unexpected token < in JSON at position 0**

On further investigation - the error is coming from .env.json which is starting with -
> <<EOT

The extra characters are generated by the commands - 

> terraform output api_env_json

and

> terraform output vue_env_dev

inside **Makefile**

**Note:**
The following command avoids the extra characters -

> terraform output -raw api_env_json

> terraform output -raw vue_env_dev

**Comment by maneeshsahu** [comment]
This is because of a change in behavior in terraform 0.14.x for outputting multi-line strings in output variables.

I am dusting-off DAC and will patch to meet the new behavior.
